apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb
subjects:
- kind: ServiceAccount
  name: sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: custom-resources-role
  apiGroup: rbac.authorization.k8s.io