apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-networks
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: otus
  source:
    repoURL: "git@github.com:Kuber-2024-02OTUS/t1mon-ggg.git"
    path: kubernetes-networks
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true