apiVersion: v2
name: kubernetes-monitoring
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts/"
    version: 58.2.1
    condition: kube-prometheus-stack.enabled
  - name: kubernetes-templating
    version: 0.1.0
    condition: kubernetes-templating.enabled
  - name: ingress-nginx
    version: 4.10.0
    condition: ingress.enabled
version: 0.0.1
appVersion: "0.0.1"
