---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-config-{{ include "templating.name" . }}
  namespace: {{ include "templating.namespace" . }}
data:
  default.conf: |
    server {
        listen 8000;
        server_name _;
        location / {
            try_files $uri $uri/ /index.html;
            root /homework;
            index  index.html index.htm;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "templating.name" . }}-volumes-cm"
  namespace: {{ include "templating.namespace" . }}
data:
{{- range $index, $key:= .Values.cmConfigmap  }}
  {{ $index }}: {{ $key }}
{{- end }}