---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen 8000;
        server_name _;
        location / {
            try_files $uri $uri/ /index.html;
            root /homework;
            index  index.html index.htm;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-volumes-cm
  namespace: {{ .Release.Namespace }}
data:
{{- range $index, $key:= .Values.cmConfigmap  }}
  {{ $index }}: {{ $key }}
{{- end }}