{{ if .Values.ingress.enabled }}
{{ $name := include "templating.name" .}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ include "templating.namespace" . }}
  annotations:
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #    rewrite /index.html /homepage permanent;
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
{{- range $index, $host := .Values.ingress.hosts  }}  
  - host: {{ $host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $name }}
            port:
              number: 80
{{- end }}
{{ end }}