kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "templating.name" . }}-claim
  namespace: {{ include "templating.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 16Mi