apiVersion: v1
kind: Service
metadata:
  name: {{ include "templating.name" . }}
  namespace: {{ include "templating.namespace" . }}
spec:
  selector:
    app: {{ include "templating.name" . }}
  ports:
    - name: index
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113