apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-config-homework
  namespace: homework
data:
  default.conf: |
    server {
        listen 8000;
        server_name _;
        location /conf/file {
            alias /homework/conf;
            autoindex on;
        }
        location / {
            try_files $uri $uri/ /index.html;
            root /homework;
            index  index.html index.htm;
        }
    }
