datasources:
  datasources.yaml:
   apiVersion: 1
   datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-loki-distributed-gateway.logging.svc:3100
      jsonData:
        timeout: 60
        maxLines: 1000
tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"