apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
    - name: nginx-default-config-volume
      configMap:
        name: nginx-default-config-homework
        items:
          - key: default.conf
            path: default.conf
  terminationGracePeriodSeconds: 4
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'wget -O /init/index.html http://example.com/index.html']
      volumeMounts:
        - mountPath: /init
          name: shared-volume
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: NGINX_PORT
          value: "8000"
      volumeMounts:
        - mountPath: /homework
          name: shared-volume
        - name: nginx-default-config-volume
          mountPath: /etc/nginx/conf.d/
      ports:
        - containerPort: 8000
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -f /homework"]

      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"